language: python
dist: xenial
sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  postgresql: "9.5"
  apt:
    packages:
    - libpq5=9.5.13-0ubuntu0.16.04
    - libpq-dev=9.5.13-0ubuntu0.16.04


install:
  - pip install -r requirements/requirements.txt


before_script:
  - psql -c "CREATE USER root WITH PASSWORD 'root'; ALTER USER root WITH SUPERUSER;" -U postgres

script:
  - python manage.py test

