# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'base de datos',
                'verbose_name_plural': 'bases de datos',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'fuente de datos',
                'verbose_name_plural': 'fuentes de datos',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripci\xf3n')),
                ('update_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='valor de actualizaci\xf3n de datos')),
                ('update_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Minuto/s'), (2, 'Hora/s'), (3, 'Dia/s'), (4, 'Mes/es'), (5, 'A\xf1o/s')], null=True, verbose_name='tipo de valor de actualizaci\xf3n de datos')),
                ('server_path', models.URLField(blank=True, null=True, verbose_name='ruta al servidor')),
                ('file_path', models.CharField(max_length=200, verbose_name='ruta a los datos')),
                ('publishable', models.BooleanField(default=False, verbose_name='publicable')),
                ('created', models.DateTimeField(verbose_name='fecha de creaci\xf3n')),
                ('last_modified', models.DateTimeField(verbose_name='\xfaltima modificaci\xf3n')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('data_sources', models.ManyToManyField(blank=True, to='core.DataSource', verbose_name='fuentes de datos')),
                ('databases', models.ManyToManyField(blank=True, to='core.Database', verbose_name='bases de datos')),
            ],
            options={
                'verbose_name': 'publicaci\xf3n',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comentarios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='responsibles',
            field=models.ManyToManyField(to='core.Responsible', verbose_name='responsables'),
        ),
    ]
