# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('data', models.TextField(null=True)),
                ('version', models.CharField(default='0.0', max_length=20, verbose_name='Version de los datos, en formato Major.minor (mm cambia incrementalmente de forma autom\xe1tica con cada nueva publicaci\xf3n de los datos, MM de misma manera pero cuando cambia la estructura de los datos)')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publication')),
            ],
        ),

        migrations.AddField(
            model_name='publication',
            name='file_format',
            field=models.CharField(blank=True, max_length=4, verbose_name='formato de los datos'),
        ),
    ]


