# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_creator', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='responsibles',
            field=models.ManyToManyField(related_name='publication_responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsables'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='update_type',
            field=models.CharField(blank=True, choices=[('mins', 'Minuto/s'), ('hours', 'Hora/s'), ('days', 'Dia/s'), ('months', 'Mes/es'), ('years', 'A\xf1o/s')], max_length=10, null=True, verbose_name='unidad de intervalo de actualizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='update_value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cada cuanto se generan/actualizan los datos', null=True, verbose_name='intervalo de actualizaci\xf3n'),
        ),
    ]
