# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161020_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_creator', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
    ]
