# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161027_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='notes',
            field=models.CharField(max_length=255, unique=True, verbose_name='notas'),
        ),
    ]
