# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_mounting_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categor\xeda', 'verbose_name_plural': 'categor\xedas'},
        ),
    ]
