# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170530_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\xfaltima modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='update_type',
            field=models.CharField(blank=True, choices=[('minutos', 'Minuto/s'), ('horas', 'Hora/s'), ('d\xedas', 'Dia/s'), ('semanas', 'Semana/s'), ('meses', 'Mes/es'), ('a\xf1os', 'A\xf1o/s')], max_length=10, null=True, verbose_name='unidad de intervalo de actualizaci\xf3n'),
        ),
    ]
