# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170713_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Publication'),
        ),
    ]
