# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-31 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170823_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='JS code',
            field=models.TextField(blank=True, null=True, verbose_name='JS code to draw the corresponding chart'),
        ),
    ]
