# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-31 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publication_js code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='JS code',
            new_name='js_code',
        ),
    ]
