# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Publication'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
