# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-07 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170831_1655'),
        ('opendata', '0002_auto_20170824_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publication')),
            ],
        ),
    ]
